#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : ksh
Version  : 1.0.6
Release  : 8
URL      : https://github.com/ksh93/ksh/archive/v1.0.6/ksh-1.0.6.tar.gz
Source0  : https://github.com/ksh93/ksh/archive/v1.0.6/ksh-1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause EPL-1.0 EPL-2.0
Requires: ksh-bin = %{version}-%{release}
Requires: ksh-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: addmake.patch

%description
The advanced software technology department has been collecting useful C
routines in a single library called libast.  libast is used by nmake, the
nmake cpp (which is mainly based on another library (libpp)), CIA
(C information abstractor from Robin Chen), and a collection of other
/bin and /usr/bin commands that benefit from concentrating functionality
in libast.

%package bin
Summary: bin components for the ksh package.
Group: Binaries
Requires: ksh-license = %{version}-%{release}

%description bin
bin components for the ksh package.


%package license
Summary: license components for the ksh package.
Group: Default

%description license
license components for the ksh package.


%prep
%setup -q -n ksh-1.0.6
cd %{_builddir}/ksh-1.0.6
%patch -P 1 -p1
pushd ..
cp -a ksh-1.0.6 buildavx2
popd

%build
## build_prepend content
unset AR
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686689594
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}

pushd ../buildavx2
## build_prepend content
unset AR
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1686689594
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ksh
cp %{_builddir}/ksh-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/ksh/c0bddab6949019048749f2d75aa59ef94b110e94 || :
cp %{_builddir}/ksh-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/ksh/85a9ba7a011c6a142fdf61cca24da1b7bbff75c8 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ksh
/usr/bin/ksh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ksh/85a9ba7a011c6a142fdf61cca24da1b7bbff75c8
/usr/share/package-licenses/ksh/c0bddab6949019048749f2d75aa59ef94b110e94
